### ISSUE TITLE
将公众号的链接发送给好友无法打开。

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#102]
目前：公众号中点击右上角“发送给好友”，发送的链接打开显示“页面未找到”。
需求：打开链接即为“注册”页面，注册成功后即为“我”邀请成功的人。

**Comment by caijiang** [comment]
什么叫做「公众号中点击右上角“发送给好友”」？
之前到底进行锅什么操作？

**Comment by deleiye** [comment]
微信公众号中，右上角有“.....”，点击后会有“发送给朋友”的选项。

**Comment by deleiye** [comment]
公众号中，在“推广，下单，我的”这些页面的右上角，都存在“.....”点击后有“发送给朋友”的选项。

**Comment by caijiang** [comment]
即微信中所有页面的分享效果要要和「分享二维码」一致咯？那样的话「分享二维码」页面还有存在的必要么？
