### ISSUE TITLE
拉卡拉支付的订单需要有“快速完成订单”功能

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#103]
目前：投融分期支付的订单有“快速完成订单”功能，拉卡拉支付的没有。
需求：把拉卡拉支付的做上“快速完成订单”功能

**Comment by caijiang** [comment]
所有已支付订单都应该拥有该选项。

**Comment by chang0022** [comment]
是否只有已支付订单才拥有 `quickDoneAble` 字段，并且值为 `true`

**Comment by caijiang** [comment]
都拥有，只有允许「快速完成」时才会是true

**Comment by chang0022** [comment]
那我现在判断是否有 「快速完成」还是通过 `item.quickDoneAble && quickUrl` 并没有根据订单状态码判断，不知这样是否可行？

**Comment by caijiang** [comment]
sure

**Comment by chang0022** [comment]
分支 en_lakala is OK.
