### ISSUE TITLE
限购相关

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#105]
* UsageStock  表示当前可用库存? 存在gap
* 每一样货品都有「计划售罄日期」(需可管理)
* 限制某一天最多只可售卖 N/d 件货品。 N 是指当前可用库存；d即为当前日期到「计划售罄日期」(包含)的天数。
* 上条数量应该是每日只计算一次。
* 对于当前日期的核算上 是参考AM 9；距离 10 19:10 是10号 11 8:30 也算10号。
* 下单之后在固定时间内（应该是配置量）若未支付则自动进入「关闭状态」
* 系统引导时 应该持续调度上一条
* 补充UsageStock  只有「待付款」和「待发货」的订单需要被算入锁定库存。

**Comment by helloztt** [comment]
1.需要在货品上添加字段 planSellOutDate 表示「计划售罄日期」
* 这个字段需要加在 Product or MainProduct 中？
* 认为类型定义为LocalDate即可满足需求
* 如果为空或者小于当前日期，则认为该设置无效？
2.计算货品的N，N=sum(剩余库存)-冻结库存
*当前UsageStock表示每个仓库剩余库存，N的计算是改在计算 UsageStock 的视图上？or 另外实时计算冻结库存；因为涉及到仓库，认为应该另外计算，UsageStock依旧表示剩余库存
*冻结库存=count(待付款 + 待发货) from MainOrder where production.id=?1
3.计算每个货品的 N/d , d=取日期（当期时间-9小时）-planSellOutDate ；d<=0?d=1
* 货品数量目前为什么数量级，在 AM 9 计算每个货品的 N/d，放入map 中？在第一次显示某个货品详情页时计算该货品的 N/d？
*[9小时]是否需要作为配置项放入spring message中
4.创建订单 MainOrderService.newOrder?
*订单付款时效设置waitPayTime(long) 作为配置项放入 spring message中
*在Transactional 前应该加上业务锁
*订单创建成功后需要建一个 Eexecutor，计算prePayTime=createTime+waitPayTime,在prePayTime后设置订单状态为关闭
*系统引导时获取所有未支付的订单，重新建立Eexecutor

**Comment by helloztt** [comment]
@caijiang 看看根据你昨天提的我整理的是否有问题或遗漏

**Comment by caijiang** [comment]
* MainProduct ;  Product所属项目为即将独立的第三方项目:物流项目；物流系统没有交易属性
* 如果为空或者小于当前日期，则认为该设置无效？ __YES__
* 货品数量目前为什么数量级，在 AM 9 计算每个货品的 N/d，放入map 中？在第一次显示某个货品详情页时计算该货品的 N/d？ __总是在需要时计算__
* 具体作为起始时刻的时刻应该是可配置的
* 创建订单 MainOrderService.newOrder? __YES__

## 其他
你的md语法需要改进，写得太丑了

**Comment by caijiang** [comment]
- [ ]  需要在货品上添加字段 planSellOutDate 表示「计划售罄日期」
* 这个字段需要加在 Product or MainProduct 中？
* 认为类型定义为LocalDate即可满足需求
*  如果为空或者小于当前日期，则认为该设置无效？
- [ ]  计算货品的N，N=sum(剩余库存)-冻结库存
* 当前UsageStock表示每个仓库剩余库存，N的计算是改在计算 UsageStock 的视图上？or 另外实时计算冻结库存；因为涉及到仓库，认为应该另外计算，UsageStock依旧表示剩余库存
* 冻结库存=count(待付款 + 待发货) from MainOrder where production.id=?1
- [ ]  计算每个货品的 N/d , d=取日期（当期时间-9小时）-planSellOutDate ；d<=0?d=1
* 货品数量目前为什么数量级，在 AM 9 计算每个货品的 N/d，放入map 中？在第一次显示某个货品详情页时计算该货品的 N/d？
* [9小时]是否需要作为配置项放入spring message中
- [ ]  创建订单 MainOrderService.newOrder?
* 订单付款时效设置waitPayTime(long) 作为配置项放入 spring message中
* 在Transactional 前应该加上业务锁
* 订单创建成功后需要建一个 Eexecutor，计算prePayTime=createTime+waitPayTime,在prePayTime后设置订单状态为关闭
* 系统引导时获取所有未支付的订单，重新建立Eexecutor

**Comment by caijiang** [comment]
实时计算[冻结库存]；
实际可用库存= UsageStock-[冻结库存]

**Comment by caijiang** [comment]
https://github.com/JoleneOL/market-manage/tree/en_mulitpart_order 购物车分支趋向稳定；建议merge过去；

微信下单页面在 wechat-service/...../orderPlace.html 中
暂不提供其他入口的下单支持。

**Comment by helloztt** [comment]
@caijiang 
* 本来计划在 **MainOrderService.newOrder** 的货品上加上 业务锁，但是传进来的是 **amounts** ,似乎没有思路？不行的话先放一放？
* 由 spring message 管理的配置项 在 **coreMessage.properties** ? 以 **market.core.service.order** 起头？ 
* 购物车分支，说明有购物车？**货品可下单数量** 是否应该也在购物车上提现？提供页面？

**Comment by helloztt** [comment]
@chang0022 orderPlace 页面
* 用户在该页面停留太长的话，商品信息可能会不准确，是否可以在商品列表加个刷新，重新获取商品信息后，移除（或者数量显示0，设置灰色）已选择的商品中库存不足的选项
* 下单时可能会不成功，比如提示库存不足或者超过购买限额之类的，所以是否可以把下单请求改为 ajax ，返回200后在跳转到支付页面，如果有异常则提示错误信息，并调用商品刷新事件

**Comment by chang0022** [comment]
@helloztt 

1. 刷新问题，可以考虑。我可做给局部刷新。

2.  其实`表单提交`改为`异步提交`，我认为校验点应该还是商品`下单数量`和`现有库存`，那么为何不在表单其他前仅仅把下单列表数据异步提交校验返回响应呢？也许这样改变现有流程较小。

3. 有一种情况是，A下单时候校验库存充足并提交订单，B同时下单。网络延迟问题先于A。那么A是否会错误？跳转到` orderFail.html`？

**Comment by helloztt** [comment]
@chang0022 
我们期望的效果是，如果存在下单失败的情况，还是返回到当前下单页面，并保留用户提交的数据，而不是跳转到`orderFail.html`。在下单前做校验，也解决不了实际问题，在创建订单是还是应该做校验，考虑这种情况：A校验成功->B校验成->A创建订单->B创建订单

**Comment by caijiang** [comment]
别想一些稀奇古怪的事儿：下单就是下单，别分为校验和创建订单。

强行拆开一个完整事务在并发环境下，事务混乱是必然发生的。
