### ISSUE TITLE
订单应可支持多种商品以及数量_ 所谓购物车

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#106]
开发分支
en_mulitpart_order

**Comment by chang0022** [comment]
GET。
有一个问题，商品数据以什么格式传给数据库？表单提交时候我需要如何组合？
我想的是一个数组，每个都是`["型号,数量", "型号,数量",...]`

**Comment by caijiang** [comment]
可以的 你放心对服务端提出要求。

**Comment by chang0022** [comment]
OK. 那就这么定了。我先开发页面去喽。

**Comment by caijiang** [comment]
所有相关的订单列表都将无法查询以下字段:
* category
* goods
* type
* amount

出库物流订单列表将无法查询以下字段:
* goods
* amount

**Comment by chang0022** [comment]
新下单列表，数据基本可工作。`goods[]`为数据输送参数。还有一些界面的交互未完。
再次询问以上无法查询的字段，那么订单列表不就是还行没啥能展示的了 （主要问微信端，PC端明白，订单列表减少很多字段。）😂 ...
那么详情页面能展示么？物流订单一样？

**Comment by chang0022** [comment]
另外 `data-price-channel` 属于商品单价的一部分么？目前暂无使用，后续添加。

**Comment by caijiang** [comment]
可以给出类似
「10台饮水机，8颗西洋参，1枚戒指」
的数据。

浅加工一下 应该可以获得类似的数组结构。

**Comment by chang0022** [comment]
OK

**Comment by caijiang** [comment]
开始进入测试平台测试，相关问题 请在本issue中提出。

正式发布需置：
- [ ]  goodName 需要足够的长
- [ ] orderBody 需为Text

**Comment by deleiye** [comment]
问题一：后台管理中，在代理下单管理里面缺少每笔订单的“购买产品”

**Comment by caijiang** [comment]
就是无法显示；后续会加入订单详情可支持。

**Comment by deleiye** [comment]
订单详情何时加入。
如果用户只下了一种产品（如量子芯片，可直接发货），我们看不到“购买产品”。就无法发货

**Comment by deleiye** [comment]
微信端，订单详情中，每笔订单右上角都会有“成功”字样（未付款也有）。
改成：“已付款”和“未付款”。二种状态。

**Comment by deleiye** [comment]
订单信息中，目前收件人姓名与手机号并排，能否做成隔行：
收件人
手机号
@chang0022

**Comment by caijiang** [comment]
@chang0022 看下这个。
