### ISSUE TITLE
物流需要有分仓发货功能

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#115]
即指一笔订单中会存在多个货品，而这些货品可能存在于多个仓库中，所以需要分仓发货

**Comment by caijiang** [comment]
将负载物流订单的可物流订单核心逻辑转移到物流模块；为了将来的手动订单铺路；
- [ ] 独立的DeliverableOrder，需在物流模块完成测试
- [ ] MainOrderDeliveredEvent不再可用，取而代之的是OrderDeliveredEvent
- [ ] 新增的OrderInstalledEvent 表明无需安装或者安装已完成，MainOrderFinishEvent应可据此调度

将增强人员对于物流系统的控制能力
- [ ] 新增手动发货类型的仓库，选择此类仓库的发货可以以输入物流编号的简单方式完成，并可命令物流状态的变化（无需接通第三方API）
- [ ] 订单详情中尽量详细的展示可控的细节
