### ISSUE TITLE
“推广”页面的分享链接和扫码存在问题

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#117]
目前发现的问题情况：
1.好友点开分享链接后，会出现“需要关注”的页面，页面会显示一个二维码框，但无法显示二维码。
2.用户通过分享链接或扫码进入后可以关注进入公众号，但点击任何按钮页面都无法显示。

**Comment by caijiang** [comment]
是所有用户都出现了这种情况 还是特定用户？

如果答案是后者可否明示哪个用户？
