### ISSUE TITLE
将分期购买区分开

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#118]

**Comment by chang0022** [comment]
我记得一个久远的issue，`我的`微信菜单拆分为`我的团队`和`我的佣金`

**Comment by chang0022** [comment]
#68

**Comment by chang0022** [comment]
我记得是三个吧 :joy:。要不然做个页面，然后是三个活动的banner，算是商城的雏形。当然还是看看 LMJ
 他们的意见，保持不变也行，我觉得 `我的` 还是需要拆分
![image](https://user-images.githubusercontent.com/6067222/29695793-73ffb484-8977-11e7-8eb1-43d766aeed74.png)

**Comment by caijiang** [comment]
哈 交付了。
