### ISSUE TITLE
当一个手机号被当做订单中收件人手机号后，无法注册

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#120]
目前：当一个手机号被当做订单中收件人手机号支付成功后，无法注册
需求：未在我们公众号注册过的手机号都应可以注册（之前后台添加的算已使用）。

**Comment by caijiang** [comment]
拒绝这个需求，会存在引导关系的错误。

当用户A 为新用户B创建了订单  视同A发展了B

之后用户C发展了用户B(B在被A引导后尚未登录)，这个时候B填写了手机号码（跟之前新用户B是一样的），那么如果成功 新用户B是A发展的还是C发展的？

**Comment by deleiye** [comment]
那用户B现在进入利每家的方式是什么：通过直接关注登陆利每家吗？手机号+密码123456

**Comment by caijiang** [comment]
未曾设计该流程.

**Comment by deleiye** [comment]
下周二例会，大家一起讨论下
