### ISSUE TITLE
在完成用户引导并到手机号码登记页面时，已知异常的处理

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#123]
2017/08/26 13:01:20 [http-nio-20000-exec-14] c.l.m.c.c.a.ControllerSupport 46 all - java.lang.IllegalArgumentException: 该手机号码已被人使用

发送验证码时会抛出该异常，需要设计一下前端如何友好地渲染这个case

**Comment by chang0022** [comment]
非`200成功`，给我一个message。我`toptip`一下不就OK？

**Comment by chang0022** [comment]
@caijiang auth_code分支
