### ISSUE TITLE
下单之后的客户关系需要更变

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#124]
* 客户信息仅作记录，它无法成为一个可登录的身份
  * 鉴于此而生成的身份应该被移除
* 成功下单是基于这个人是否拥有一个成功的订单，而跟客户没有关系
* 客户并不会与任何代理体系产生关联
* 所有身份关系将因此重新生成

**Comment by deleiye** [comment]
1. A帮B下了一个订单，使用了B的手机号，支付成功但没有发货完成。后来B扫A码进入，使用B手机号还是显示“系统错误”
