### ISSUE TITLE
“限购”功能测试发现的问题

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#125]
1.在限购发布后，购物车功能只能购买一种产品，无法购买多种。显示“系统错误”
2.购买产品后，微信端的限购台数没有递减。
3.在后台修改“限购清算时间”后，下单或者分期下单的页面都没法进入（然后我重置了一下测试平台，还是这样）

**Comment by helloztt** [comment]
限购清算时间是应该是整点，区间为[0,23]

**Comment by deleiye** [comment]
在哪里可以设置限购的时间段

**Comment by helloztt** [comment]
货品修改里有一个计划售罄时间

**Comment by deleiye** [comment]
下单成功后，后台的“仓储管理”中货品的库存量并没有相应的减少

**Comment by helloztt** [comment]
下单成功，可售库存减少；发货成功，仓库库存减少

**Comment by deleiye** [comment]
当设置计划售罄时间后，限购台数计算存在问题。(例如：空气净化器，选择售卖一天，限购台数为49。当选择二天，限购数量为33。）

**Comment by deleiye** [comment]
刚刚将“限购清算时间”设置到15.   到了十五点后显示的限购台数并没有更新

**Comment by helloztt** [comment]
已发布到测试平台

**Comment by deleiye** [comment]
举例：将售卖天数设置为一天，限购台数为89。售卖天数为二天，限购台数变成了32.。设置五天，限购台数变为29。
就算其中存在着冻结库存，但每天限购数量也不应这样变化

注：当前库存中是否缺少“今日入库数量”的计算

**Comment by deleiye** [comment]
已测试完成，目前不存在问题
