### ISSUE TITLE
自动移除无效身份

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#127]
无效身份的定义为:
*  非代理商
*  没有成功支付过一笔订单
*  非管理员

若该身份存在引导者，则分别将推送消息给引导者
* 还有5分钟删除时: 预警即将移除
* 删除时，通知已删除

@deleiye 需要你的协助就这2个消息选择消息模板，同时调整操作，选定模板之后直接添加并将较长的模板编号PO到issue上;不然我每次都得找个半天。

**Comment by deleiye** [comment]
已添加模板：预警移除：a54aoLbDL0PE5UHzrUp-aqG8odneAyf2VVDsZOzeeXk
                     删除：mHa78XXneZ-xigJg6SVyvX7qlWADKvC8nSrVNO-T8Yw
