### ISSUE TITLE
关于货品限购数量的计算

### ISSUE THREAD

**Issue by helloztt** [JoleneOL/market-manage#128]
以下 **今日** 为此时相对于清算时间的日期，比如此时时间小于清算时间，那么此时其实为昨日
以下 **冻结** 是指未支付和未发货的订单。订单发货后，冻结数量将减少，库存总数量也将减少；订单关闭后，冻结数量将减少，库存总数量不变

_期望_限购数量 = (今日开始时的库存总数量 - 今日开始时的冻结总数量) / (今日相对于预计限购时间D) - 今日订单数量（未关闭，下同）
_目前_限购数量 = (当前库存总数量 - 当前冻结总数量) /  (今日相对于预计限购时间) - 今日订单数量

* 关于 「当前库存总数量」：目前未提供某一时间区间的库存量计算，所以改成了「当前库存总数量」。
  * 当前库存总数量 = 今日开始时的库存总数 - 今日发货的库存总数(今日订单发货数量 + 今日之前订单发货数量)
* 关于 「当前冻结总数量」：
  * 当前冻结总数量 = 今日开始时的冻结总数量 - 今日之前订单关闭数量 - 今日之前订单发货数量  - 今日订单发货数量+ 今日下单数量

* 今日开始时的库存总数量 - 今日开始时的冻结总数量

= 当前库存总数量 + 今日发货库存总数（今日订单发货数量+今日之前订单发货数量）- （当前冻结总数量 +今日之前订单关闭数量 +  今日之前订单发货数量 - 今日下单数量 + 今日发货数量）

= **当前库存总数量 - 当前冻结总数量** - 今日之前订单关闭数量（增加定时关闭订单功能后，这一项可以忽略不计） **+ 今日下单数量**（状态不是关闭的订单数量）

= 暂且把这个等式命名为**ZTT限购数量**

--------------------------分割线举例子-------------------------
假设库存为100，D=2
1.昨日有1个订单待付款A1，1个订单待发货A2，这时计算今日限购数量
* 今日库存100，今日前冻结库存2（A1+A2）当前库存总数 100，当前冻结总数2
  * 期望限购数量 = (100-2) / 2
  * 目前限购数量 = (100-2) / 2
  * ZTT限购数量  = (100-2)/2
2.今日有1个订单待付款B1，1个订单待发货B2，1个订单已发货B3，昨日订单A2发货，这时计算限购数量：
* 当前库存总数98（100-A2-B3）,当前冻结总数3（A1+B1+B2）,今日冻结数量2（B1+B2）,今日下单数量3（B1+B2+B3）
  * 期望限购数量 =（100-2）/ 2 - 2
  * 目前限购数量 = （98 - 3）/2 - 2
  * ZTT限购数量 = (98 -3 + 3) / 2 -2

-------------------------例子说完了---------------------------------
综上所述，似乎 **ZTT限购数量=当前库存总数量 - 当前冻结总数量 + 今日下单数量** 比当前算法更为准确？

**Comment by caijiang** [comment]
先点一个赞，然后慢慢看。

**Comment by caijiang** [comment]
……………………我看不懂…………………………脑子扰迷糊了；

为什么库存量会跟订单量存在关系？2者单位都不一致的。

当前库存总数量的算法过于复杂了，没必要获取「今天开始时的当前库存量」，也没必要获取今天已经下单的量（即忽视掉 在管理员动手设置【售罄时间】前的订单）

**Comment by helloztt** [comment]
库存数与冻结数的计算基于什么时候库存有变动，什么时候冻结数有变动。
库存数的变动：订单发货，库存数减少；（库存量和订单量的关系）
冻结数的变动：订单发货，冻结数减少；下单（未付款，未发货），冻结数增加
那么：
当前库存数=今日开始时库存数-今日前库存数的变动-今日库存数的变动
=今日开始时的库存总数- 今日之前订单发货数量-今日订单发货数量 ；

当前冻结库存=今日开始时冻结数-今日前冻结数的变动+今日冻结数的变动
=今日开始时冻结数-(今日前订单关闭数+今日前订单发货数)+(今日订单数:未付款+未发货+已发货-今日已订单发货数)；
