### ISSUE TITLE
“我要提现”界面增加 “收益提现规则”

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#141]
“我要提现”界面增加 “收益提现规则”，规则已形成word。可在qq群找到 @chang0022

**Comment by caijiang** [comment]
老常 你觉得作为哪种格式提供给你是最好的？
我觉得应该是PDF为佳。
word在不同的设备效果很不相同，非常不认同它作为标准格式。

**Comment by chang0022** [comment]
我目前可以HTML翻译一遍，就如先前的协议。PDF和Word都是不适合用户查阅吧。如果是下载看的话。移动端两种格式都需要第三方APP。
我想，需要添加一个文档管理。然后包括协议。合同。规则。
但一直没想好如何管理。

**Comment by caijiang** [comment]
https://www.idrsolutions.com/online-pdf-to-html5-converter/

试用了下 效果非常好；我看看它们有没有提供API化解决方案 酱紫就可以引入到项目中。

**Comment by caijiang** [comment]
网页端友好的始终也应该只有html

**Comment by chang0022** [comment]
@caijiang 我刚才试了试。效果有点像Axure。宽高是根据实际文档来定死的。但实际移动端和原始文档的还有一定区别的。

**Comment by chang0022** [comment]
@caijiang 我感觉通过样式和富文本比较靠谱。协议在我开了一个新的分支里面。
