### ISSUE TITLE
“分佣体系”测试的问题

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#142]
1.master直接发展用户，用户下单后升级为“代理4”。代理4直接下单或者发展用户下单，代理4都不应该拿到1%平推费，而是master直接拿到3%平推费。因为master推荐了代理4

**Comment by caijiang** [comment]
发布新更新
请注意使用后台的重新结算功能 重新结算已结算订单。

**Comment by deleiye** [comment]
A为master，推荐了B从用户逐步升级到代理3。 B在代理3身份时推荐了C，C也逐步升级到了代理3。这时C直接下单。B只拿到了1%平推费，A拿到了2%。
正确的应该为A拿1%。B拿2%
