### ISSUE TITLE
代理商升级功能中，审核成功或失败都应该消息

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#143]
明天我去找模板

**Comment by deleiye** [comment]
名字：审核结果通知
模板ID：NN7SBN3h-Z7WRnZjWmSHtV9R8MCsDtoIpIHsX8f--Tc

看能否在审核结果一栏加上审核拒绝的原因

**Comment by caijiang** [comment]
在
正式平台 「利每家」
以及测试平台 「利每家管理平台」
都添加一份模板

**Comment by caijiang** [comment]
and 附加模板内容；这样开发人员就不必再去登录查看该模板信息了。
以后添加模板消息都按照这个套路来。

**Comment by deleiye** [comment]
添加完成
