### ISSUE TITLE
每次进入公众号不应该都需要登陆

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#15]
登陆页面，现在每次都需要登陆，应该为登陆一次后就不需要登陆。

**Comment by caijiang** [comment]
事实就是不需要登录的
BUT
https://github.com/JoleneOL/market-manage/wiki/%E6%B5%8B%E8%AF%95%E5%B9%B3%E5%8F%B0#%E6%95%B0%E6%8D%AE%E4%B8%B4%E6%97%B6%E6%80%A7

**Comment by caijiang** [comment]
另一个原因是，一个帐号总是只能被一个微信号自动绑定的
比如 你使用微信登录 master ；在之后你都可以自动登录master

直到某天 另一个人使用微信登录 master
