### ISSUE TITLE
后台权限管理

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#152]
|   级别       | 管理内容 |
| -----------|-----------|
| 超级管理员  | 最高权限|
| 管理员    | 可查看后台数据，但不可操作      |
| 财务     |代理商佣金管理    |
| 客服经理      |经销商管理，订单管理，产品中心，供应链管理     |
| 客服      | 订单管理，物流管理，查看经销商      |
| 运营     |产品中心以及商城的后台管理     |

**Comment by caijiang** [comment]
解决方案已发布至线上；该issue所描述的情况应该需要保留以备将来扩展使用；辛苦下 @deleiye 将该信息迁移到wiki上去。
