### ISSUE TITLE
投融家快速完成订单中物流时间应该都可选

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#153]
发货时间可随意选择，但送达时间只能选今日及以后。送达时间应该也可随意选择

**Comment by chang0022** [comment]
@deleiye 目前发货时间是最大到今日。送到时间最小是今日。我不明白你的 `发货时间可随意选择`和`送达时间应该也可随意选择`？打个比方，发货时间可以写下个星期？

**Comment by deleiye** [comment]
发货时间目前是没问题，主要是送达时间，送达时间应该也设置为最大到今日

**Comment by chang0022** [comment]
不对吧。今天发货。我送到时间应该是最小是今天吧。

**Comment by chang0022** [comment]
我认为的是送达时间是最小是发货时间吧。

**Comment by deleiye** [comment]
实际中我们走线下，送达后还需要有安装时间。如果只能以今天为最小时间，那么就会存在提交时间与实际时间不符合的问题。

**Comment by deleiye** [comment]
系统中不是以你发货时间作为送达时间的最小时间。而是以操作当日时间为最小时间

**Comment by chang0022** [comment]
我一脸懵逼，根据你的意思是发货时间和送达时间无关系？

- 发货时间最大是今日是否可以？
- 送达时间的不该是一个未来的日期？
- 发货时间作为送达时间的最小时间是否合理？

最好举个栗子 😂

**Comment by deleiye** [comment]
前面描述的不准确，屡一下

目前系统中不是以发货时间作为送达的最小时间，而是以操作的时间来作为送达最小时间，这样就存在选不到真实的送达时间的情况。

发货时间最大是今日，没有问题
送达时间该是一个未来的时间，没问题

**Comment by chang0022** [comment]
@deleiye 运总。我现在更加懵了。
目前`发货时间`设置是过去至今天。`送达时间`是今天至未来。
1、`发货时间`：过去-今天。`送达时间`：今天-未来
2、`发货时间`：过去-今天。`送达时间`：`发货时间`-未来
例子：
8月1号发货。`送达时间`只能填写今天至未来。
那么问题来了。
实际上可能是8月1号发货，9月1号送达。但现在无法实现。
你的需求是`送达时间`的范围应该以`发货时间`为起始？你的第一条意思好像是第二种。但最后的那条又像第一种。

**Comment by deleiye** [comment]
2、发货时间：过去-今天。送达时间：发货时间-未来
需求是这条
