### ISSUE TITLE
9.8   需求

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#156]
在“爱心天使”时为积分，等级为代理4到代理0时为佣金。佣金的分成方式不变

1. “普通用户”身份去除，只存在“爱心天使”和代理4-代理0（注册即为爱心天使，不下单还是会被移除，不下单还是无“二维码”）

1. “爱心天使”首次购买的某类商品，都无法获得20%积分，20%将属于“他”的所属者

1. 当“爱心天使”第一次购买过某类商品后，第二次购买同类商品即可获得20%积分，当积分到达100%即可选择兑换等值现金或机器。任务可以一直循环进行（1.但兑换现金只限于第一次任务.  2.每类商品都可做任务）

1. 爱心天使买了某类商品，如果他的推荐人（爱心天使以上）没有买过此类商品，那么推荐人无法获得佣金，佣金属于爱心天使的所属者

1. 如果一笔订单中包含“爱心天使”首次购买的商品，那么这笔订单则算他第一次购买（就无法拿到这笔订单中各商品任务的20%积分）。

1. 爱心天使A推荐了爱心天使B，那么B首次下单，A可以获得此类商品的20%任务积分。

**Comment by caijiang** [comment]
任务类的调整只是之前新手任务的补充。

**Comment by caijiang** [comment]
判定是否为同样的商品的依据是  #155

**Comment by caijiang** [comment]
可否将第3条和之前的新手任务合并或者独立建档；本次开发并不会包含第3条。

**Comment by deleiye** [comment]
测试的问题：1. 爱心天使首次下单的某类商品，代理4未下过单，代理4没获得佣金。但爱心天使第二次下同类商品，代理4获得了佣金。

**Comment by deleiye** [comment]
下的都为优化宝，已设置“结算名称”

**Comment by deleiye** [comment]
问题2：代理4-代理0首次购买商品没有获得佣金。他们应该可以获得佣金

**Comment by deleiye** [comment]
但是首次购买无法获得佣金只适用于爱心天使，不适用于代理4-代理0

**Comment by caijiang** [comment]
哦 那需求又要调整过了？

**Comment by deleiye** [comment]
没有改变，可能之前没沟通好
