### ISSUE TITLE
产品的参数

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#160]
- 产品名称 *

- 品牌

- 型号 *

- 计量单位（台/片   之类的）

- 重量

- 尺寸

- 颜色分类

**Comment by helloztt** [comment]
需要提供：货品分类、属性、属性值
* 货品分类（对应你写的 产品名称）
* 分类下面有2种属性：扩展属性和规格属性，在详情页列表显示的为扩展属性（如品牌），区分同一分类不同货品的决定性属性为规格属性（如颜色）
*属性值为属性的可选项，比如 颜色属性 下可分为 黑色，白色，随机色。规格属性下必须要有属性值，扩展属性如果是输入框类型的可以没有属性值

货品分类请提供：分类名称
扩展属性请提供：属性名称，展示类型（输入框or选择框）,是否是必填的，权重
规格属性请提供：属性名称，权重
属性值请提供：属性值名称，权重

说明：之后维护这些数据时只能添加和删除，不能做修改，所以尽量现在就确定好

**Comment by deleiye** [comment]
|产品名称  | 规格属性（颜色） |扩展属性（型号/品牌/重量/尺寸/单位） |
| -----------|-----------|-----------|
|量子立式净水机  | 黑色/白色|型号：SCRO-200BA/SCRO-200BB，品牌：尼维柯，重量：22kg，尺寸：435x325x1200（mm），单位：台 |
|量子厨下净水机    |白色 |型号：M537R，品牌：爱普兰，重量：12.2kg，尺寸：495x270x580（mm），单位：台|
| 量子空气净化器     |香槟色|型号：ESL-HM01，品牌：利每家，重量：5.3kg，尺寸：425x255x490（mm），单位：台 |
| 量子食品优化宝 |金色/银色 |型号：SP70A-HS/SP70B-HS，品牌：利每家，重量：32kg，尺寸：465x480x760（mm），单位：台 |

1.  其他还有什么美容喷瓶，项链，芯片啊，不好填写属性，到时候我们自己增加吧。现在这4个是我们主要的商品
