### ISSUE TITLE
需要禁止某种商品进入分佣体系的功能

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#165]
需要禁止某种商品进入分佣体系的功能。用户购买此种商品后，用户以及推荐人等不获得佣金。

**Comment by caijiang** [comment]
上次我提过这个需求不是被否决了么？

**Comment by deleiye** [comment]
董事长现在又有需求：购买某种商品后，不被分佣。

**Comment by caijiang** [comment]
那就合并到新分佣体系中吧；暂不开发，下次开会再提出一次 可能就被再度否决了。
