### ISSUE TITLE
商城购物车开发

### ISSUE THREAD

**Issue by chang0022** [JoleneOL/market-manage#167]
老方案：
![image](https://user-images.githubusercontent.com/6067222/30728800-5e9eabc8-9f8d-11e7-8205-2398903b2bdc.png)
新方案：
![image](https://user-images.githubusercontent.com/6067222/30729715-3f6a5534-9f94-11e7-8682-556bcb047748.png)

新老方案的差别在于数据是客户端存储还是服务端。
1.  商品的数据有时效性。本地存储的数据往往也实际数据不相符。
2.  至于每次还需要客户端取出提交服务器校验。增加了客户端的复杂性。客户端增删改查不是那么的方便。
3. 本地存储如果不同手机登录同一个账号，数据不能共享。衍生的问题是万一以后做APP的话。还是需要微信端和APP数据同步。

**新方案确实增加了服务端的工作量，但客户端会更好的处理视图交互而非数据。**
**当然第二个方案也是参考淘宝的处理方式，毕竟本地存储不是那么的靠谱**
@helloztt 婷姐怎么看
@caijiang 蒋哥怎么看

**Comment by caijiang** [comment]
我比较倾向于客户端储存方案；只不过存储的数据应该调整为  仅仅保存商品的ID以及数量；
然后要求服务端提供更多restful的方案 获取商品的属性；以及是否持续有效。

这个机制的容灾能力强并且可以应对可预见的几乎所有需求；

**Comment by chang0022** [comment]
我比较倾向于服务端储存方案；理由有点像CMS组件数据的客户端的处理。取出来给服务器。服务器有给回来。客户端再存起了。一来一回的 😂 
本地存储`保存商品的ID以及数量`，也不足以渲染整个购物车页面，我打开页面拿出数据给服务端，然后服务端再给一些数据。再渲染。还不如打开页面直接给出整个购物车的数据、渲染或者服务器渲染来的爽快。
而且，就如说我，数据的同步这个问题无法解决。如果以后有个APP（万一），购物车的数据还是需要同步吧。
而且如果服务器端`仅仅保存商品的ID以及数量`。岂不也一样。
客户端存这一点点数据毫无啥作用，最终还是需要拜托服务器。

**Comment by chang0022** [comment]
搜索解决方案：
可能采用 `客户端储存方案，只不过存储的数据应该调整为 仅仅保存商品的ID以及数量`，同时也会有服务端的数据交互。
我先采用客户端的方式进行开发。看后续疗效。
