### ISSUE TITLE
下单界面用户协议无法滑动浏览以及经销商升级协议不可点击

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#173]
发现问题的设备包括但不限于:
* iPhone 6s
* iPhone 7
* iPhone SE

Android 三星则是可以滑动的。

**Comment by chang0022** [comment]
这个问题我 Chrome 遇到了。我排查一下。

**Comment by caijiang** [comment]
协议丢失等待需求部门的供应；
