### ISSUE TITLE
批货订单列表界面需要优化

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#189]
微信端用户输入#货款。得到链接后进入的“批货订单列表”界面中“可用预付货款”的显示需要优化。

**Comment by caijiang** [comment]
分支  en_185 微信新增的一个页面..名字我居然一下子想不起来了。

是有这么一点丑。

**Comment by caijiang** [comment]
订单列表的数据格式是跟普通订单一致的；所以列表区的就不关注了  只关心头部那些信息。
