### ISSUE TITLE
订单管理中的商品类型筛选字段查询有问题

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#192]
商品类型的筛选字段中选择“全部”后筛选并不会出现全部，而是不显示任何商品。

**Comment by chang0022** [comment]
You ask @caijiang . 才哥，不是 `goodId ` `全部`的情况未处理？目前 `value `应该为 `0`。改为 `-1`？还是你安排处理吧。

**Comment by caijiang** [comment]
好的，服务端允许传入**0**为「不过滤货品」
