### ISSUE TITLE
查看经销商中，对每个代理商的“查看”操作的需求

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#193]
1. 查看中显示：代理商姓名，级别，手机号，地址，身份证，营业执照，以及更改名字，改名前和改名后的名字。

1. 货款记录（流水和余额）

1. 发展成功的下线（下单成功）

**Comment by chang0022** [comment]
好的。运总。

**Comment by caijiang** [comment]
另增
* 允许修改名字
* 允许修改手机号码
* 允许修改上线(只有一次机会)

btw:  贷款流水可以参考 我之前开发的佣金流水（嘿嘿）

**Comment by caijiang** [comment]
可否在周会前将页面初制出来？ 以便在周会时过一下这个页面。

**Comment by chang0022** [comment]
可以
