### ISSUE TITLE
表单提交时候的小问题

### ISSUE THREAD

**Issue by chang0022** [JoleneOL/market-manage#2]
input等表单 `readonly` `disabled` 设置问题。
有些字段是无法修改的的 `readonly` `disabled`，都可以从页面层面阻止修改。但提交的时候 `readonly` 会随着表单提交。`disabled` 则不会。
我的issue：
1、默认的字段是否还要提交？
2、`readonly` 其实可以通过 `F12` 改浏览器代码，然后修改提交字段值。

**Comment by caijiang** [comment]
1，默认字段最好还是提交下，实在做不到也无所谓
2，你有张良计，我有过墙梯；readonly 只是一种界面方式，服务端总有办法的
