### ISSUE TITLE
新增货品类型需求

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#213]
货品名称：空气净化器演示工具包
型号：YS01
规格：一套    
价格：800      
@helloztt

**Comment by helloztt** [comment]
在此做个备份，测试服务器上如果没问题即可执行@caijiang

insert into producttype (DTYPE,DISABLED,NAME,PARENT,PATH,PARENTPRODUCTTYPE_ID) values('ProductType',0,'空气净化器演示工具包',0,'|0|',null);
insert into propertyvalue(disabled,icon,value,weight,propertyname_id) values(0,null,'一套',0,1);
insert into propertyname_propertyvalue(PropertyName_ID,propertyValueList_ID) select propertyname_id,id from propertyvalue where value ='一套';
--手动查询
A=select id from producttype where name ='空气净化器演示工具包';
B=select id from propertyvalue where value ='一套';

insert into producttype_propertyvalue(ProductType_ID,propertyValueList_ID) values (A,B);
