### ISSUE TITLE
佣金列表页面，悬浮需可显示详情

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#24]
![image](https://user-images.githubusercontent.com/7594914/26963393-ed0ce4d6-4d1e-11e7-92c6-2871df09b8e7.png)

现在在佣金列表，看到的是基于订单的收益，而没有具体区分这笔X%是来自何处的；这对于理解收入的来源多少会存在疑惑。同时也可以提高系统的可调试性。

所以可以在此悬浮的时候 可以展示n条 小记录。
数据结构有:
比例
事由
金额

哦，这是微信界面，不应该悬浮；那点击下方拉出一块如何？

等领导觉得OK，这块就可以开展

**Comment by deleiye** [comment]
做成不需要下拉的，直接在销售收益下面加收益的类型：四种类型：1、直接销售（20%，25%，30%，35%），2、下级销售（5%，10%），3、平级推荐（1%），4、区域服务（2%）。如果收益包含多种收益类型，那就在下方显示多种。

**Comment by caijiang** [comment]
效果上应该是 点击某一佣金记录
则：
1. 隐藏其他佣金记录详情(上推或者上拉)
1. 显示（上拉或者下推）该佣金记录的详情；

提高该问题的优先级；因为很多问题都是基于这个issue 才可以继续推进

**Comment by deleiye** [comment]
徐总他们的要求是，无需上拉或下拉，直接在销售收益下方显示显示详情。

**Comment by caijiang** [comment]
否决。

你可以预见这个场景，基于我们分佣的复杂度，用户看到的情况将可能是一个屏幕都还没看完一个订单；
而这个情况被徐总真实看到的时候，他又会提出新增一个「某一个订单我获取了总的多少佣金」的新需求；

所以只能这么做。

**Comment by caijiang** [comment]
你可以跟徐总商量一下

**Comment by deleiye** [comment]
使用下拉，现在我们只存在4种销售收益的类型。
