### ISSUE TITLE
我的佣金页面无法下拉。

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#27]
当我的佣金中，出现多笔佣金时无法下拉看到下面的佣金。

**Comment by chang0022** [comment]
该问题原型暂时没有问题。我找一找原因。

**Comment by caijiang** [comment]
这个问题会比较麻烦 @chang0022

**Comment by caijiang** [comment]
尽快处理

**Comment by chang0022** [comment]
可否提供一个多笔佣金的账户。我现在原型是没问题的。

**Comment by chang0022** [comment]
https://imgchr.com/i/kigPS 我原型的录屏。

**Comment by chang0022** [comment]
虽然 mock数据已经设置延迟 1s，但还是没有真实数据可靠。样式 display: none; 引起的一些了BUG。痛定思痛，修改了页面的交互方式来规避这个BUG。
