### ISSUE TITLE
datatables 排序问题

### ISSUE THREAD

**Issue by chang0022** [JoleneOL/market-manage#3]
参数配置
columns 有 name 的别名设置
例如：
```
{
      "title": "安装机型", "data": "type", "name": "type"
 }
```
然后请求的数据就变成
![image](https://cloud.githubusercontent.com/assets/6067222/25708377/e72cabc2-3118-11e7-81d4-9d55cdf087ae.png)

`order[0][column]:1` ->  `columns[1][name]:code`
https://www.datatables.net/manual/server-side 全部参数的相关信息，可惜没有 `order[0][name]:xxxx` 的参数。
另对应数据的排序规则，是否是服务端决定？

**Comment by chang0022** [comment]
虽然不是直接给出，但也可以获取到哪一列进行了排序。所以列排序后，应该没问题。

**Comment by chang0022** [comment]
排序解决。https://datatables.net/extensions/colreorder/examples/
后续添加。工期紧张~

**Comment by caijiang** [comment]
OK，有原始数据就可以
