### ISSUE TITLE
平级推荐费结算有问题

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#30]
现在无平级推荐时，平级推荐费归属到了该级的总代或代理或经销。正确的应该为：无平级推荐时，平级推荐费归属利每家。有平级推荐才给他们结算平级推荐费。

**Comment by caijiang** [comment]
「利每家」这个角色怎么体现在系统中？

**Comment by deleiye** [comment]
徐总说搞一个利每家营销中心，将多余的平推费都放到这里

**Comment by caijiang** [comment]
反过来说，如果不存在这个营销中心会怎么样？

资金：没有人获得佣金，自然该佣金就是系统所有的；

报表？徐总需要的是他意外获取到的佣金报表么？

**Comment by caijiang** [comment]
我感觉是所谓的“平级推荐”认知上出现了偏差；可否整个wiki详细解释定义下你们经常提及的“平级推荐”

**Comment by caijiang** [comment]
按照之前的理论
https://github.com/JoleneOL/market-manage/wiki/%E4%BB%A3%E7%90%86%E4%BD%93%E7%B3%BB

系统是绝对不会存在无平级推荐奖励的情况

**Comment by deleiye** [comment]
平级推荐指的是，总代推荐总代，或者代理推荐代理，经销推荐经销。只有这三个平级推荐。现在测试时发现无平级推荐时，这1%也会被总代或代理或经销拿到。应该为，无平级推荐时，这1%归属利每家， 也就是归属系统
