### ISSUE TITLE
公司后台员工管理页面产品化

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#34]
因「退款功能」依赖该功能模块

**Comment by chang0022** [comment]
GET

**Comment by caijiang** [comment]
这个提前点
大致数据有
id,用户名，真实姓名，工号，微信昵称（非录入），角色（可以多选 原型上随便写几个）,是否启用

还有其他什么的你使劲儿想想。

操作上有
调整角色，禁用|启用

**Comment by chang0022** [comment]
OK。产品管理原型已经丢上去了。我把微信的新需求和原型今天处理好，就有限动工 员工管理。
讲真我以为员工管理的意思是 叫 LMJ 的员工进行管理而非员工管理页面。。。:joy:
