### ISSUE TITLE
下单支付成功后即可看到佣金

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#39]
下单支付成功后即可看到佣金，提现还是按照之前隔月提现的规则。

**Comment by caijiang** [comment]
谁提的这个问题？？
是否从未登录过公司后台？
订单必须完成才可以看到佣金

**Comment by deleiye** [comment]
徐总提出的。改为下单支付成功后即可看到佣金。

**Comment by deleiye** [comment]
另一个同样性质的问题：现在应该是下单安装成功后显示爱心天使。但现在提出要求：支付成功即可成为爱心天使
