### ISSUE TITLE
成为“爱心天使”后可登陆微信端

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#48]
成为“爱心天使”后可登陆微信端

**Comment by deleiye** [comment]
1.沿用代理商微信界面     2.「我的团队」界面显示存在默认页      3.「我的订单」界面显示还是我下的订单，没有订单用默认页

**Comment by caijiang** [comment]
> 1，登录之后看到什么？是沿用代理商微信界面么？
2，如果问题1答案是「是」的话， 「我的团队」界面显示什么？ 爱心天使要查看旗下的总代？
3，如果问题1答案是「是」的话， 「我的订单」界面显示什么？ 是我下的订单还是给我的订单？
4，顺便确定代理商登录和爱心天使登录之后的 设备显示问题。
至于我为什么会提及这些问题，因为这些问题比想象中更难。
比如问题3，
如果显示的是「我下的订单」，那么作为爱心天使首次登录 订单列表必然是空的（可以接受？）
如果显示的是「给我的订单」，那么自己下的订单此处是无法看到的（很尴尬……）；甚至某一天自己晋级成为代理商之后，「咣当」一下原来看到的订单都不见了。
如果显示的是「既显示我下的订单，又显示给我的订单」，那么会有很大一部分订单会同时会被2个人看到（一个是下单人，一个是收件人），so 订单的管理权归谁？谁可以负责任地让这个订单进入退款退货售后状态？

引用下群里的发言，特地在此mark，确定新需求并不在乎逻辑。

**Comment by caijiang** [comment]
已上线，检查后请关闭
