### ISSUE TITLE
微信公众号关注后自动推送消息

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#52]
微信公众号新用户关注后自动推送消息

**Comment by caijiang** [comment]
是固定的消息？还是需要管理？

**Comment by caijiang** [comment]
另外，该功能会导致原公众号管理部分功能失效

**Comment by deleiye** [comment]
应该是需要管理的图文消息，因为后期内容会更新

**Comment by caijiang** [comment]
更好的办法去完成该功能：
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444738734

关键API "获取素材列表","获取永久素材" 则可以读取 「关注后发送图文消息」的图片以及url
