### ISSUE TITLE
添加”推广“微信菜单

### ISSUE THREAD

**Issue by chang0022** [JoleneOL/market-manage#55]
推广，替代`我的团队`位置
1、还未下单，引导下单
2、已经下单，显示为推广二维码
等待原型
@deleiye 小叶请补充说明

**Comment by chang0022** [comment]
对了，**推广**功能的优先级最高，高于现在的**物流**。

**Comment by deleiye** [comment]
1、“推广”替代“我的团队”。然后把“我的团队”放到“我的”里面。
      “我的”里面将“我的设备”改为“我的团队”。
2、注册后的用户，需在下单后才能分享二维码。在用户下单支付后发送一条通知告知用户可进行分享。
  也需等待原型。

**Comment by caijiang** [comment]
简单描述下我对于推广的需求猜测:

### 老用户层面（包括爱心天使，代理商）
在分享界面可以分享自己的推广链接
此处缺少:
* 图标
* 分享描述

### 新用户层面（就是扫码了二维码或者打开了分享链接的人）
如果这个用户是老用户，则只是一个引入到我们微网页的行为。

反之，则该用户成为我们的匿名用户（很自然的成为老用户的下线）。

匿名用户可以完成下单，但只能给自己下单，同时需要校验手机号码。
完成后则视作正式用户（并以该手机号码为用户名）。

**Comment by caijiang** [comment]
ID: 1yi+ID

**Comment by caijiang** [comment]
订单体系增加 受益者
所有奖励都只给予「受益者」而不是再是「下单者」

通知体系也需要调整，如果「下单者」不是「受益者」则不展示佣金之类的信息。

非正式用户 点击推广 只能看到海报

**Comment by caijiang** [comment]
* 标题:利每家
* 描述:您的好友****邀请您加入利每家
* logo:https://cdn.lmjia.cn/lmjia_logo_1.png
