### ISSUE TITLE
关于下单 “推荐人” 交互方式的探讨

### ISSUE THREAD

**Issue by chang0022** [JoleneOL/market-manage#6]
首先声明并非当前开发有难度问题。仅仅探讨是否可行。

**问题：** 模糊查找的功能是否适合移动端下单？

现在的交互如徐总所说。如通讯录招人。但现在问题是，通讯录的中用户体系是用户自己的，而我们现在给他展示的推荐人是属于我们的。简单说就是，可能让用户看到其他用户的个人信息。
**探讨：** 用户是否有”权利“知道其他用户的信息。我个人认为不能然其他用户可以看到不该他看的数据。
**解决：** 手机号简单处理。如 156****5000
**问题：** 手机号相似并且重名~ 可能选错人。

**个人体验：** 作为用户，我并不希望下单的时候填写一系列的东西，简单便捷。那把推荐人输入手机号 替换成 邀请码那种如何？把长长的手机号用短数值代替。
**流程：** 每个用户都用一个唯一的邀请码 （数字+字母 4或者5位）。然后可以 ` 一键粘贴` 。方便发个别人或者自用。

**验证：** 正常的异步表单验证，可以做到在提交之前。告诉用户是否查无此人或者某某某。

**Comment by caijiang** [comment]
我都纠结了……

**Comment by chang0022** [comment]
其他改动还带商榷。但我觉得邀请码要友好于手机号。:1234:
