### ISSUE TITLE
07.05 会议纪要

### ISSUE THREAD

**Issue by chang0022** [JoleneOL/market-manage#63]
主要会议还是关于用户-推广-下单一系列 @caijiang 
**三个角色**： A、未注册未下单（普通用户）；B、已注册未下单（普通用户）；C、已注册已下单（爱心天使以上）

**流程**
A ：点击（公众号菜单）-> 注册（新页面）->（成功）->显示注册前点击的菜单页面
A1-> 点击的是`推广页面` ->角色转换为 B
A2 -> 点击的是 `下单页面`->（成功）-> 文字提示 **系统**关闭该页面 -> 角色转换为 C

B ： 推广页面，海报页面，海报A，按钮 `成为合伙人` -> 跳转 `下单页面` ->（成功）-> **系统**关闭该页面 `wx.closeWindow();` _（好像是这个方法）_ -> 角色转换为 C

C：推广页面，二维码页面，右上角按钮 `合伙人升级` （原`赚钱计划`）-> 点击 ->`海报页面`（同页不同报），海报B，按钮 `升级合伙人 ` ->升级合伙人页面->（成功）->推送信息和**系统**关闭该页面

下单页面：
添加花呗分期checkbox。

@deleiye 缺失补充

今晚前端原型完成

**Comment by caijiang** [comment]
### 升级前页面update.html

缺少公司名称,进货款0,代理费即升级费用,默认时间1年

支付成功后应该展现 支付成功页面（缺）。

### 升级时 应该展现 「正在审核」的信息

### 公司后台可以管理升级申请
如果是省总代，其实是区，以当前市级代理作为上级；弹出输入框 「自定义代理等级」

同时为了应对误输入，公司后台可以维护申请信息。

### 通过都需要通知
### 支付也要通知

**Comment by deleiye** [comment]
通过通知：OPENTM205211943
支付通知：OPENTM409997458

**Comment by caijiang** [comment]
「我的」界面涉及到的团队因素调整过大 会消耗更多的开发时间。

**Comment by deleiye** [comment]
周日前需上线  "推广"   "注册"（完善个人信息）  "下单"   "升级合伙人"  。
"我的"  需要改为上拉的模式。

**Comment by caijiang** [comment]
5号决定一项功能，9号就上线；不止是不可能，简直是XXX。

(XXX)可以被代替为任何粗话。

我绝对无法达成这个目标。

**Comment by caijiang** [comment]
升级时 应该展现 「正在审核」的信息

**Comment by caijiang** [comment]
@chang0022 升级时 应该展现 「正在审核」的信息;  update.html 应该加一个 由body属性控制的一个全屏幕遮罩；

**Comment by chang0022** [comment]
这个问题我想过，但我想是一个新页面正在审核一类的话术，还是当前页面不可编辑。我和 @deleiye 他们沟通沟通

**Comment by caijiang** [comment]
公司地址不使用标准的哪个地址格式么？

**Comment by chang0022** [comment]
那个？地址？目前移动端和PC端的地址格式好像是不同的，因为两种插件。

**Comment by caijiang** [comment]
类似下单那个地址即可；

**Comment by caijiang** [comment]
@chang0022 先处理这个页面吧
一个是地址 允许下单一样的选择地址
另一个是 提交form的时候 如果选择的是经销商（就是需要支付的） 可以弹出输入框输入线下支付信息（没有就无需输入）；

**Comment by chang0022** [comment]
@caijiang 升级页面？地址怎么讲？下单地址？
现在爱心天使升级经销商可以在线支付也可以申请下线支付。我做个checkbox 处理

**Comment by caijiang** [comment]
update.html 的公司地址，输入时体验跟下单时差不多最好
checkbox 处理也可。

**Comment by chang0022** [comment]
GET.

**Comment by caijiang** [comment]
还有昨天关于正在「审核」的问题；现在决策是如何？

**Comment by chang0022** [comment]
LMJ 的没有太明确，也没原型。我打算是进入后还是升级的页面，但无法操作。无法输入。无按钮。有一些提示性文字等。

**Comment by caijiang** [comment]
「正在审核」的话 我直接跳 updateSuccess.html 好了。

**Comment by chang0022** [comment]
那  `updateSuccess.html`  也一页三用，申请成功、支付成功和正在审核，

**Comment by chang0022** [comment]
@caijiang 我新加了一个 `waitFor.html` 页面，感觉后续正在审核也要大变样~
