### ISSUE TITLE
"爱心天使"点击"推广"显示的页面不正确

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#65]
"爱心天使"点击"推广"应该显示自己的的二维码，右上角有"升级合伙人"的按钮，里面显示的为升级合伙人海报。
"普通用户"点击"推广"显示"成为合伙人"的长海报，点击成为合伙人按钮去到下单页面。

**Comment by caijiang** [comment]
我擦
到底哪个地方不正确啊

**Comment by deleiye** [comment]
目前情况: 1. 爱心天使点击推广显示的是升级合伙人的海报。2. 普通用户点击推广的流程现在微信端无法操作。
需要做成:1. 爱心天使点推广，显示为个人的二维码，右上角为升级合伙人按钮，里面为海报 2. 普通用户点推广显示的为"成为合伙人"海报。

**Comment by caijiang** [comment]
我不太了解 "无法" 这个词

你点击推广的时候 你的手机操作系统提示你不可以？

**Comment by deleiye** [comment]
现在注册进去不就是爱心天使吗。
所以微信端现在无法看到普通用户点推广可以看到什么页面

**Comment by caijiang** [comment]
....无法理解

**Comment by deleiye** [comment]
我们存在二张海报：一张“成为合伙人”，另一张“升级合伙人”。
期望流程：普通用户进来注册后，点推广，看到的为“成为合伙人”海报，点击下方“成为合伙人”按钮，去到下单页面。               下过单的用户点推广，看到自己的二维码，右上角有“升级合伙人”按钮，进去为“升级合伙人”海报。
