### ISSUE TITLE
新注册用户应为"普通用户"

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#66]
现在新用户注册进去后显示为"爱心天使"，应该显示为"普通用户"。

**Comment by deleiye** [comment]
希望稍微快一些修改完成，他们明天要开始招商。

**Comment by caijiang** [comment]
哪个地方？描述得精准些啊

**Comment by deleiye** [comment]
扫码进入后注册完成的用户，在"我的团队"中显示的级别为"爱心天使"，显示错误。正确的应该显示为"普通用户"。下过一单才显示为"爱心天使"
