### ISSUE TITLE
升级规则

### ISSUE THREAD

**Issue by chang0022** [JoleneOL/market-manage#69]
| 角色         | 经销商    | 市代理 | 省代理 | 
| -----------|-----------|---------|---------|
| 爱心天使  | 付款 / 申请|  申请   |申请   |
| 经销商      |    N/A       |  申请   |申请   |
| 市代理      |    N/A       |  N/A    |申请   |

@deleiye 小叶，确认一下

**Comment by deleiye** [comment]
还存在升级为“省代理” @chang0022

**Comment by deleiye** [comment]
对了
