### ISSUE TITLE
几个问题，我就合并在一个issue里了

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#7]
1. 下单的时候 应当校验购买数量大于0
1. [微信端](https://joleneol.github.io/market-manage/wechat-service/src/main/resources/wechat-view/error/systemMaintain.html)和[PC端](https://joleneol.github.io/market-manage/web/src/main/webapp/error/systemMaintain.html)分别添加了系统维护的错误页面
1. 当然希望添加更多错误页面，比如404,500等经典场景
1. 新增了微信端的[订单支付页面](https://joleneol.github.io/market-manage/wechat-service/src/main/resources/wechat-view/pay.html)，PC端的还没做
1. [微信端登录页面](https://joleneol.github.io/market-manage/wechat-service/src/main/resources/wechat-view/login.html)应当支持手机验证码登录；可以切换2种

**Comment by chang0022** [comment]
GET! :ok:
