### ISSUE TITLE
公司后台安装地址无法显示

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#70]
公司后台的代理商下单管理中，安装地址这一项现在显示为[object Object]，正确的应该显示出详细的安装地址。

**Comment by chang0022** [comment]
![image](https://user-images.githubusercontent.com/6067222/28200898-1cdde9a6-68a1-11e7-9582-5d079879fa33.png)
![image](https://user-images.githubusercontent.com/6067222/28200946-53546d7a-68a1-11e7-9d6f-a7de69cf45fc.png)

**Comment by chang0022** [comment]
PC和微信端地址统一格式为：
address:浙江省 杭州市 滨江区
fullAddress:智慧E谷
原始PC格式为：浙江省/杭州市/滨江区
@caijiang
