### ISSUE TITLE
公司后台的下单时间与拉卡拉后台的支付时间不一致

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#71]
目前：公司后台的下单时间与拉卡拉后台的支付时间不一致，有的订单相差好几个小时。
期望：我们公司后台显示的下单时间与拉卡拉后台支付的时间保持一致。

**Comment by caijiang** [comment]
1;   期望这个时间一致干球

2；现在是因为系统不知名的故障导致数据库卡死出现的几个小时的差距。
