### ISSUE TITLE
分成中目前少了市代理的分成

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#72]
现在公司代理层级为: 省代理，市代理，经销商，爱心天使。省代理直接下单应获得35%分成。
但目前公司的一位省代直接下单只有30%分成。正常应该获得35%。

**Comment by caijiang** [comment]
伪需求
需要认真思考下需求是什么，按照你们不断折腾技术的角度来看，需求应该是你们需要一个地方让你们可以设置关于分成参数；而不是今天通知技术调整成这个，明天换个花样。
