### ISSUE TITLE
升级成功后的代理等级名称不对

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#78]
目前： 升级到市代理后，我的团队中，等级会显示为代理商。升级到省代理可以自定义代理等级，但是在我团队的全部里面还是显示为区县总代
期望： 升级到市代理之后，显示代理等级的地方都应该显示为市代理。省代理都显示为省代理

**Comment by caijiang** [comment]
又出现新需求了？

**Comment by deleiye** [comment]
不是，因为现在的"市代理"不是以前的"代理商"吗。系统中还是叫做代理商，现在需要名称统一显示为市代理。
省代理（之前的区县总代）也是一样，统一显示为省代理。

**Comment by caijiang** [comment]
这个需求有人说过？哪里？发出来看看？

**Comment by caijiang** [comment]
一直在让你们发需求说明 流程说明 ；非得换以一天八遍的口述方式进行
我现在开发基本都是以蒙圈为主 猜对了算运气 猜错了重做。

**Comment by deleiye** [comment]
上周开会定了最新的代理等级:省代理（之前的区县总代），市代理（之前的代理商），经销商，爱心天使。

**Comment by caijiang** [comment]
具体说流程

代理商怎么变成的 ‘市代理’
固定的？灵活的？

如果是灵活的从哪个阶段控制的？

开会定下来的是忽悠人的套路 又没有提及具体的流程。

**Comment by deleiye** [comment]
"代理商"这一等级我们之前不是关闭了吗。现在需要将其名称改为"市代理"，开通这一等级
。是固定的。
这样代理层级就变成了省代，市代，经销商，爱心天使。省代直接销售获得35%分成。
