### ISSUE TITLE
升级合伙人页面存在问题

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#79]
目前： 当我以“经销商”或“市代理”的身份进入升级合伙人时，页面最下方还是会显示30000的费用。
期望： 当我以“经销商”或“市代理”的身份进入升级合伙人时，页面最下方不显示30000元的的费用。

**Comment by caijiang** [comment]
老常看下这个问题
现在那几个 option 不见得会存在；服务端渲染加入了条件。

**Comment by chang0022** [comment]
这个问题我页面有考虑，身边为“经销商”或“市代理”时，将属于爱心天使的HTML，服务隐藏即可。操作方式类似之前的一页两用方式。
![image](https://user-images.githubusercontent.com/6067222/28298028-99ddf7de-6ba3-11e7-82b6-e7c1b38cff7b.png)
