### ISSUE TITLE
滚动刷新的一个数学问题

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#8]
在当前场景中

绝大部分都是 先由服务端渲染一部分数据（0-19）；然后通过AJAX获取更多通过page控制
但是如果切换了tab,比如在我的团队中；我选择了级别；这个时候就是完全由Ajax给数据，但很可惜给的page依然是1开始的。

我的意见是放弃服务端渲染，第一部分数据(0-19)也是通过AJAX获取。

这样避免此类的数学问题，也避免了当前tab和其他tab需要不同的逻辑，导致前端以及后端的复杂度都提高。

**Comment by chang0022** [comment]
其实这个问题仅仅出现在我的团队中这个页面。而且选择了级别后确实会从1开始，是我特意处理了一下。[myTeam.js](https://github.com/JoleneOL/market-manage/blob/master/wechat-service/src/main/resources/wechat-resource/assets/js/myTeam.js#L97) 原因是，该页面的tab 切换别其他的不同，处理起来略有麻烦，而且我想的是该页面的使用频率不一定很高。每次切换都从第一页开始，不失一个这种的想法。
但 personCenter 下的所有 tab代码都是独立的。每个都有各自的页面记录。不会印象其他。

**Comment by chang0022** [comment]
我的团队页面的tab切换有点像 电商页面里面的不同属性。如京东页面：手机分类中 我划到第7页，然后我选择了品牌属性，页面会回到顶部并第1页的数据，然后我取消品牌属性，页面局部刷新到全部数据，而且还是第1页，而非我们之前划到的第7页。

现在 我的团队 我想是 页面第一次是服务端渲染，后面交给Ajax即可。

而其他页面 如 personCenter 它们的 tab 都是独立的代码块。第一次是服务端渲染，后面也是 Ajax即可。

**Comment by caijiang** [comment]
2个都做问题不大；定义 page = 页索引(从0开始，不传默认为0）
即传入page=1等于要第二页

**Comment by caijiang** [comment]
2次渲染依然感觉很蛋疼…………

personalCenter.html
我已经把服务端渲染的代码去掉了

page也从0开始了；还存在一个gap就是 现在只有滚动屏幕才可以载入数据，可否加入自动加载？

**Comment by chang0022** [comment]
Impossible~ 我页面加载第一次就请求一次页面。原型模拟没有出现上述问题。我再查一查。

**Comment by caijiang** [comment]
页面是加载了；那个 数据请求没有进行。
