### ISSUE TITLE
商品价格不影响订单金额

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#82]
商品价格可以改，但不影响订单金额

**Comment by caijiang** [comment]
更新脚本
`
UPDATE `mainorder` as mo JOIN `maingood` as g on g.`ID`= mo.`GOOD_ID` JOIN `mainproduct` as p on g.`PRODUCT_CODE`= p.`CODE`
   SET mo.`GOODTOTALPRICE`= p.`DEPOSIT`+ p.`INSTALL`,
       mo.`GOODCOMMISSIONINGPRICE`= p.`DEPOSIT`,
       mo.`GOODNAME`= p.`NAME`;
`
