### ISSUE TITLE
鉴于其他业务的更进，产品商品架构需要调整

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#84]
### 一种产品可能会有参数接近的几种形态
比如相同产品不同颜色吧啦吧啦的
#### 长，宽，高还有重量

**Comment by caijiang** [comment]
开发分支 haier

**Comment by chang0022** [comment]
开发的时候想到了一个问题，一个商品是否可以对应多个类目。比如，量子净水机，是否可以分为两个类目，**量子**和**净水机** @caijiang 我想开辟一个类目（tag）管理的页面，当然添加商品页面的时候也可以选择或者添加。

**Comment by caijiang** [comment]
你想的是对的。应该需要。后头做商城肯定会用到。

**Comment by caijiang** [comment]
产品中心 应当包括:
货品管理 ( 货品是仓储，运转的最小单位，拥有实际的各种属性，比如长宽，大小，品牌吧啦吧啦，货款，服务费……）
商品管理（商品是用于经营的最小单位，当然它是跟货品有直接关联的，既然是做生意用的 自然可以调整价格（目前还没有，哈哈） ）
类目管理 基于现在的开发计划，这块暂时压后。
