### ISSUE TITLE
投融家流程

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#86]
* 用户从投融家APP获得初审核准码
* 用户从界面中输入「初审核准码」并且获得校验则系统认可支付完成（不结算佣金）--同时需要将订单信息提交给投融家
* 发货安装完成则提交订单完成信息
* 信审结果；不通过的话 -- 发客服  客服--信审再度申请--需要上传附件
* ~~发标纯通知性~~
* ~~满标纯通知性~~
* 结算 -> 结算佣金

**Comment by caijiang** [comment]
https://kuanyes.quip.com/gA1PAfnTc3TP#temp:Cg0N1hHfPQ3O_j5lwokz4_164

相关技术手册

**Comment by caijiang** [comment]
后台管理-订单管理 需添加「投融家按揭码」管理.

* 展示信息有 订单编号，按揭码，用户姓名，状态（未申请，信审中，信审拒绝，结算中，已结算）
* 只会展示已使用并且已安装到位订单的按揭码；
* 界面上的操作有 信审申请（只有针对状态：未申请和信审拒绝）此时可以选择上传任意附件。

**Comment by caijiang** [comment]
后台管理-订单管理页面

快速完成交易功能
如果支付方式是投融家，则在选择使用该功能时需要额外录入数据:
* 物流公司
* 物流仓库
* 库存余量
* 发货时间
* 送达时间(默认今日)

**Comment by caijiang** [comment]
开发分支 en_trj

**Comment by chang0022** [comment]
后台管理 - 订单管理页面 
![image](https://user-images.githubusercontent.com/6067222/28775077-c6c6bf5e-7622-11e7-958b-d03cd8c4f0c5.png)

相关操作说：
`修改` 是**未付款**之前 还是**未发货**之前都可以？
`快速完成`是啥意思？是**未付款**之前么？
`重新结算`是啥？

订单管理操作比较多，我需要了解一下`订单状态`下的对应的操作。
可能状态码是需要确定下来的。#89

**Comment by caijiang** [comment]
快速完成  你可以认为它是「发货+安装」

因为现在供应链尚未完成建设；所以快速完成是一个技术上的代替品。

显而易见，它只可以处理「已支付」的订单。

**Comment by caijiang** [comment]
重新结算 是用于佣金的结算，只要是 已支付 或者 其后续状态 都可进行。

**Comment by chang0022** [comment]
**重新结算**  对于第三方分期活动也如此么？ 如花呗与投融家，应该没有已支付的概念吧。
**重新结算**  应该仅仅作用于 普通订单吧？

**Comment by caijiang** [comment]
订单流程是统一的
花呗投融家 仅仅是一种支付手段
所以不会改变流程。

也就是**重新结算**是可以工作于所有订单的。

**Comment by caijiang** [comment]
后台管理-订单管理 需添加「投融家按揭码」管理.

提交信审申请时除了可以选择上传文件之外还必须录入
* 安装人员
* 安装公司
* 安装人员手机
* 安装时间 yyyy-MM-dd HH:mm:ss(默认今日)

**Comment by caijiang** [comment]
@deleiye 
在订单完成（安装完成）之后，我们需要向投融家发起信审申请。
或者在我们信审被拒绝之后需要向投融家发起信审申请。

此时我们需要向客服发送一个微信模板消息。
你懂我的意思了吧。

**Comment by deleiye** [comment]
向投融家发起信审申请消息模板编号：OPENTM205474002

**Comment by caijiang** [comment]
* 产品添加「是否投融家专售」字段；只有选择了该字段 才可显示在「投融家下单」界面中
* 产品添加【手续费】字段
* 在使用投融家进行下单时，隐藏订单总金额；结算金额按 【设备款】+【手续费】而非传统下单的（【设备款】+【服务费】）；佣金结算始终只使用【设备款】

**Comment by chang0022** [comment]
我在想 投融家 算是产品中的活动类型 还是支付类型 或者？因为如果添加 「是否投融家专售」一个表单组件，那么后续有 xxx活动。那就又要添加。
所以，我能可能还需要一个类似 「活动（支付）管理」的页面，类同 类型管理 #84

**Comment by caijiang** [comment]
恩 你的想法更好些。晚上一起讨论。

**Comment by chang0022** [comment]
所以呢，产品中心要大干一场。

**Comment by caijiang** [comment]
现在贼尴尬了
你产品中心的commit跟提现混淆在了一起
无法单独拉到en_trj去了

**Comment by caijiang** [comment]
我可能先在en_trj 建立新的数据模型；然后管理功能暂时不上。管理就我们手动动数据库。
等en_trj正式发布；在和之前的页面合并开发管理功能。

**Comment by chang0022** [comment]
master分支现在产品+仓储+物流+提现。。。

**Comment by caijiang** [comment]
* 增设 活动管理 活动可以跟产品产生关联；多对多；即多个产品可以参与一个活动，一个产品也可以参与多个活动
* 投融家下单将只显示参与了「投融家」活动的产品
* 普通下单将不再显示参与了「投融家」活动的产品
* 投融家下单只允许数量1

**Comment by caijiang** [comment]
下单 ->  购买,分期
