### ISSUE TITLE
业务状态码

### ISSUE THREAD

**Issue by chang0022** [JoleneOL/market-manage#89]
我在开发订单的时候感觉急需业务状态码，不然都是**魔法数字** `1 2 3 4...`
目前指定需要一些通用的状态码：

- 待付款
- 待发货
- 已发货
- 派单中
- 已收货
- 待安装
- 已安装
- 订单完成
- 订单异常
等等

花呗是否有一些状态码？
投融家的一些状态码？
- 待核对
- 信息审核中
- 审核已通过
- 审核未通过
等等
还有后续的。
有些状态期待 LMJ 进行指定。
现在JS开发在多状态的列表处理的时候简直可怕。
@caijiang

**Comment by caijiang** [comment]
https://github.com/JoleneOL/market-manage/wiki/Conversion
请在该WIKI中维护
