### ISSUE TITLE
_logisticsManage.html 的路由问题

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#91]
_logisticsManage.html 有3个tab 框。

基于某些需求，用户可能需要被导航到特定的tab；可否加入 _logisticsManage.html#xx  的支持。

btw: _logisticsManage.html  页面的其他tab框被我暂时注释了；因为服务端尚未实现……修改的时候 请注意这点。

**Comment by chang0022** [comment]
GET

**Comment by caijiang** [comment]
not work...

**Comment by chang0022** [comment]
Not work?

**Comment by caijiang** [comment]
好了；应该是JS缓存问题。
