### ISSUE TITLE
仓储管理的数据载入问题

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#93]
http://test.lmjia.cn/manageStorage

在执行数据刷新 比如特定项的搜索时 会产生这方面问题。

原型上问题无法展示。

![image](https://user-images.githubusercontent.com/7594914/29103693-bf7eb5a8-7cf3-11e7-9289-5468073ee433.png)

数据也是确实收到的。

**Comment by chang0022** [comment]
draw参数有问题。客户端给的是3。你返回的是1。
