### ISSUE TITLE
详细的物流信息

### ISSUE THREAD

**Issue by caijiang** [JoleneOL/market-manage#95]
好像市面上都存在一些查询工具 可以查询相关物流单号的详情。

小叶看下日日顺有没有 可用的查询成品；这样我们就不用费时费力的从那些 稀奇古怪的事件状态中 整理出好看而且用户熟悉的物流详情了。

**Comment by deleiye** [comment]
http://www.kuaidi100.com/all/rrs.shtml?from=openv

这个网址可查询物流详情
