### ISSUE TITLE
佣金免税提现额度

### ISSUE THREAD

**Issue by deleiye** [JoleneOL/market-manage#97]
~佣金免税提现的额度为首笔订单支付成功后的24小时内所支付的订单总额。~

**Comment by caijiang** [comment]
* 提现 提供发票20%
* 每一个商品都可以提供一个新手任务，累计直接推广满5个即可完成，完成之后就可以享受赠送商品或者同等价格现金同时扣除等额佣金
* 执行提现之后 未完成任务记录清零。
* 任务只可以完成一次。

**Comment by deleiye** [comment]
当“爱心天使”第一次购买过某类商品后，第二次购买同类商品即可获得20%积分，当积分到达100%即可选择兑换等值现金或机器。任务可以一直循环进行（1.但兑换现金只限于第一次任务. 2.每类商品都可做任务）
